### ISSUE TITLE
New version is broken

### ISSUE THREAD

**Issue by franciscop-invast** [ctimmerm/axios-mock-adapter#113] opened 2018-02-08 07:56 UTC
It seemed [the new version](https://github.com/ctimmerm/axios-mock-adapter/pull/109/files) totally broke `axios-mock-dapter`. Here is the issue:

```js
if (handlers[method].length) {
  handlers[method].forEach(function(item, index) {
    if (item[0] === handler[0]) {
      handlers[method].splice(index, 1, handler);
    }
    handlers[method].push(handler);
  });
} else {
  handlers[method].push(handler);
}
```

It is **checking the uniqueness of a request only by the method and path** (item[0] is the path) while ignoring the rest of it. It considers these equal:

```js
POST /login {}
POST /login { "username": "franciscop", "password": "123" }
```

And these too:

```js
GET /users
GET /users?id=1
```

Not only that, but it **removes** the previous ones and THEN performs the in-depth check for the latest one, so it is very likely to return 404! If you make the post request to `/login` with no body, it will remove the first one, and then **not** match the second one because it does not have the body.

I do not think these two should be treated the same. They were treated differently before. So I am facing new 404s now that I upgraded to the latest release. I am pretty sure that this is the same issue as https://github.com/ctimmerm/axios-mock-adapter/issues/111 but let me open this separately until confirmed.

**Comment by ctimmerm** [comment] 2018-02-08 07:59
Yep, I'm working on a fix. I'll close this one since it's a duplicate of #112.

**Closed by ctimmerm** 2018-02-08 07:59 UTC
