### ISSUE TITLE
Trying change the response of an onGet later in the test doesn't work

### ISSUE THREAD

**Issue by sinner** [ctimmerm/axios-mock-adapter#328] opened 2022-02-02 16:48 UTC
Hi team, your project is very useful. Thank you very much.

I have the following test code:

```js
describe("Test PreferencesView.vue component", () => {
    const mock = new MockAdapter(axios);
    let store;
    const dataList = [1, 2, 3];

    beforeEach(() => {
        store = GlobalStore;
        mock.reset();
        mock.onGet(/data/).reply(200, dataList);
    });

    it("should handle success response", async () => {
        const wrapper = shallowMount(MyComponent, {
            store,
            localVue
        });

        await flushPromises();

        expect(wrapper.vm.dataList instanceof Array).toBeTruthy();
        expect(wrapper.vm.dataList.length).toBe(dataList.length);
    });

    it("should handle errors properly", async () => {
        mock.onGet(/data/).replyOnce(500, { message: "Server Error" });

        const wrapper = shallowMount(MyComponent, {
            store,
            localVue
        });
        const spyHandleError = jest.spyOn(wrapper.vm, "showGenericErrorNotification");
        wrapper.vm.$nextTick();

        await flushPromises();

        expect(spyHandleError).toHaveBeenCalled();
    });
```
The idea of the test is setting up a default 200 HTTP response for all the request over `/data/` regex URL expression in the `beforeEach` method, but I would like to change that behavior in some test cases.

The weird thing here is that the first test pass successfully, but, the second test when I'd like to test my component against an API error it turns out that the API doesn't return the expected 500 error, it always returns the 200 HTTP OK response that was configured in the `beforeEach` method.

I need to achieve this because there are some other test cases that depend on that 200 HTTP OK response.

Thank you very much in advance.

**Comment by JeffreyStevens** [comment] 2022-05-26 20:34
I am having this problem as well in my unit tests. I want to test both success and error responses in the same set of tests.

**Comment by ctimmerm** [comment] 2022-05-27 09:30
duplicate of #257

**Closed by ctimmerm** 2022-05-27 09:30 UTC
