### ISSUE TITLE
Types are broken with CJS/Typescript

### ISSUE THREAD

**Issue by orgads** [ctimmerm/axios-mock-adapter#371] opened 2023-04-03 13:49 UTC
```typescript
import MockAdapter from 'axios-mock-adapter';
```

This is transpiled into:
```js
const axios_1 = require("axios");
const axios_mock_adapter_1 = require("axios-mock-adapter");
// ...
const mockAxios = new axios_mock_adapter_1.default(axios_1.default);
```

Following the changes in fd982cd0fc, this no longer builds.

```
error TS1259: Module '".../node_modules/axios-mock-adapter/types/index"' can only be default-imported using the 'esModuleInterop' flag
index.d.ts(81, 1): This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

**Comment by marcbachmann** [comment] 2023-04-12 09:38
This should be fixed with v1.21.4

**Comment by orgads** [comment] 2023-04-13 06:57
It's not fixed, sorry.

**Comment by mgrejanin** [comment] 2023-06-14 03:33
Also getting typing errors while using v1.21.4 as mentioned here in this [comment](https://github.com/ctimmerm/axios-mock-adapter/issues/367#issuecomment-1590403475)

**Comment by remcohaszing** [comment] 2023-06-14 06:42
Thanks for pinging me in the other issue @mgrejanin.

If you run into this, this **probably** means you should use one of these:

- For libraries or Node.js applications:
  ```ts
  import MockAdapter = require('axios-mock-adapter')
  ```
  and/or
  ```jsonc
  {
    "compilerOptions": {
      "module": "node16"
    }
  }
  ```
- For web applications:
  ```jsonc
  {
    "compilerOptions": {
      "module": "esnext",
      "moduleResolution": "bundler",
      "esModuleInterop": true
    }
  }
  ```

However, since `MockAdapter` has a static property `default`, using a default import should technically work as well. This is fixed by #372.

**Closed** 2023-06-14 06:56 UTC

**Comment by mgrejanin** [comment] 2023-06-14 12:34
@remcohaszing It's fixed in v1.21.5. Thank you!

**Comment by buronix** [comment] 2023-06-20 15:56
Not sure, but I´m using v1.21.5 and have the exact same problems.
I´m not sure, but I´m pretty sure that my typescript version is constantly confusing MockAdapter as a class and namespace.
Is there any reason why the types namespace and class name should be exactly the same? 
eslint is confuse, typescript is confuse, even I´m confuse about it.

**Comment by remcohaszing** [comment] 2023-06-20 16:17
By using the same name for the namespace and the value, it's possible to export types in a project that uses `module.exports =`. :)

What's not working for you? Can you make a public reproduction?
