### ISSUE TITLE
Not working after Node 18 Upgrade

### ISSUE THREAD

**Issue by AustinMutschler** [ctimmerm/axios-mock-adapter#359] opened 2023-01-13 20:51 UTC
Hello I have the following setup:

"axios": "0.21.2"
"axios-mock-adapter": "1.21.2",

We recently attempted to upgrade to Node 18 but after doing so and running our test, most Axios calls are trying to make an actual network request where they were previously mocked. One of my URL params does have {} in it like `?projection={"test": 1}` but I am not sure how that would be an issue after our Node 18 update.

**Comment by marcbachmann** [comment] 2023-04-12 16:02
I've been running node 18 since a while and haven't observed that issue.
Node 18 is also in the test matrix.
I'll close this for now until there's a reproduction.

**Closed by marcbachmann** 2023-04-12 16:02 UTC
