### ISSUE TITLE
The newest version mock(1.18.1) can not run on IE11

### ISSUE THREAD

**Issue by nttd-haohe** [ctimmerm/axios-mock-adapter#254] opened 2020-03-25 15:03 UTC
Browser:IE11
OS:Win10
babel-polyfill is working, and the 1.7.0 is OK.

The vue page can not be displayed. Because the error below.

> TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them

If the mock's response has data, the error will be throw.

**Comment by chaitu9916** [comment] 2020-03-25 16:39
Try version 1.16.0 with Axios 0.18

**Comment by SylRob** [comment] 2020-04-13 07:39
I have the same problem on IE11 with 1.18.0 (1.17.0 working fine)
but with a different error report.
```
Invalid Calling Object error
```

**Comment by bewildergeist** [comment] 2020-05-07 08:40
See also #255, probably same issue. The issue is clearly with `axios-mock-adapter` from `1.18.0` and newer.

**Comment by Chicopower** [comment] 2020-06-04 13:32
Same problem here.
"axios-mock-adapter": "1.18.1" = Not working with IE11
"axios-mock-adapter": "1.17.0" = Working with IE11

On my side, using the mock adapter 1.18.1 just don't mock my calls with IE11.
Working OK with other browsers.

**Comment by mjhenkes** [comment] 2020-06-04 17:58
This has been fixed: https://github.com/ctimmerm/axios-mock-adapter/pull/262
It just needs to be released.

@ctimmerm Pretty Please? 😬

**Comment by tomer78** [comment] 2020-06-25 06:41
Hi,
Thank you for the fix for ie11 error.
Is there any estimation on when the fix will be released?

**Comment by ctimmerm** [comment] 2020-07-18 08:51
Fixed in 1.18.2

**Closed by ctimmerm** 2020-07-18 08:51 UTC

**Comment by mjhenkes** [comment] 2020-07-18 13:45
Thanks @ctimmerm !
