### ISSUE TITLE
Example of passing arguments

### ISSUE THREAD

**Issue by mandysimon88** [ctimmerm/axios-mock-adapter#15] opened 2016-08-22 17:44 UTC
Hi,

Trying to write an onPost that checks the arguments passed, but not having any luck. Dug through your source code, but what would be really helpful would be at least one example in the README of using arguments in the request:

My Code
```
Axios.post('/api/estimate', {
      _id: '123'
})
```
This "works" but doesn't check arguments:
```
mockServer.onPost('/api/estimate').reply(200, { text: 'stuff to reply with' })
```
This doesn't work:
```
mockServer.onPost('/api/estimate', {
  _id: '123'
}).reply(200, { text: 'stuff to reply with' })
```
Also doesn't work
```
mockServer.onPost('/api/estimate', {
  request:
    _id: '123'
  }
}).reply(200, { text: 'stuff to reply with' })
```
Also doesn't work
```
mockServer.onPost('/api/estimate', {
  body:
    _id: '123'
  }
}).reply(200, { text: 'stuff to reply with' })
```

Etc. You get the idea. Would be really helpful if you could provide just one simple example... Thank you!

**Comment by ctimmerm** [comment] 2016-08-23 12:20
Hi!

> ```
mockServer.onPost('/api/estimate', {
  _id: '123'
}).reply(200, { text: 'stuff to reply with' })
```

That should work, an example can be found at the very bottom of the README. The example there is a bit a bit unclear, I'll try to improve it. The tests for this feature can be found here: https://github.com/ctimmerm/axios-mock-adapter/blob/master/test/basics.spec.js#L112

Can you check what version of axios-mock-adapter you're using (request body matching was only added in 1.6.0) and, if possible, post a complete example that shows this part not working so I can debug it myself?

**Comment by mandysimon88** [comment] 2016-08-23 15:45
I’m using axis-mock-adapter v. 1.6.1, just installed.

It would definitely help to improve the example…

My original source code:
```
// App.js
...
saveEstimate() {
    return Axios.post('/api/estimate', {
      _id: this.state.estimate.documentId(), // can just substitute this with an integer for debugging purposes; this code is actually working in production
      estimate: this.state.estimate.serialize() // creates a JSON version of the object, also unit-tested and working in production
    })
}
```
The test file:
```
import Axios from 'axios'
import MockServer from 'axios-mock-adapter'
import App from '../../../client/components/App'
import EstimateDocument from '../../../server/schemas/EstimateDocument'
import Estimate from '../../../client/models/Estimate'

describe('with database', () => {
  let mockServer

  beforeEach(() => {
    mockServer = new MockServer(Axios)
  })

  describe('App', () => {
    let component
    let estimate

    beforeEach(() => {
      component = new App()
      component.setState = () => {}
      mockServer.onPost('/api/estimate').reply(200, { estimate: new EstimateDocument(component.state.estimate) })
    })

    it('saves the estimate to the database', (done) => {
      component.saveEstimate().then(() => {
        expect(component.state.estimate.documentId()).toBeTruthy()
      }).then(done).catch(done.fail)
    })
  })
})
```
All of the above is working; I just can’t add in anything to the `mockServer.onPost` to check the arguments and not just the URL. It’s also really hard to debug since I’m unsure how to grab a hold of the request itself and log it out for example.

**Comment by ctimmerm** [comment] 2016-08-27 16:13
It's quite hard to see for me what's going wrong with all the other stuff that's going on. I've created a working, runnable example here that reduces your use case to just the essentials:

```js
var axios = require('axios');
var MockAdapter = require('axios-mock-adapter');

var mock = new MockAdapter(axios);

mock.onPost('/api/estimate').reply(200, { text: 'stuff to reply with' })

axios.post('/api/estimate', {
  _id: '123'
})
  .then(function(response) {
    console.log(response.data.text);
  });
```
Could you perhaps modify this example so that it reproduces the problem you're experiencing?

If you want to inspect the request that comes in to the mock adapter, you can do so like this:

```js
mock.onPost('/api/estimate').reply(function(config) {
  console.log(JSON.stringify(config, null, 2));
  return [200];
});
```

**Comment by ctimmerm** [comment] 2016-10-14 08:53
Since it has been hanging around for some time I'll close this one for now. Please reopen the issue if you have some runnable example where the issue is reproduced.

**Closed by ctimmerm** 2016-10-14 08:53 UTC
