### ISSUE TITLE
Works with auth?

### ISSUE THREAD

**Issue by hdrdavies** [ctimmerm/axios-mock-adapter#16] opened 2016-08-25 09:08 UTC
Great library! Working great for most of my tests.

On this occasion I'm trying to test my async login actions in redux as follows:

action:

```
export const submitLoginData = (data, location) => dispatch => {
    dispatch(loggingIn());
    return axios({
        method: 'get',
        url: '/api/authorize',
        auth: {
            username: data.email,
            password: data.password
        }
    })
```
etc.

test:
```
            let postData = {
                email: 'Joe',
                password: 'Bloggs'
            };

            let responseData = {
                token: 'foo'
            };

            mock.onGet('/api/authorize')
                .reply(200, responseData);

            store = mockStore();

            return store.dispatch(actions.submitLoginData(postData, '/'))
                .then(() => {
                    actual = store.getActions();

                    expected = [
                        { type: actions.LOGGING_IN },
                        { type: actions.LOGIN_SUCCESS }
                    ];
                    
                    expect(actual).to.eql(expected);
                    done();
                });
```

However I'm getting a 404 error. Could this be because I need to configure the route to correctly respond to HTTP basic auth? Has anyone achieved this previously?

**Comment by ctimmerm** [comment] 2016-08-27 15:49
Nothing special needs to be done, for the mock adapter this is just a request like any other.

I think this is a reduced (working) example of what you're trying to do:

```js
var axios = require('axios');
var MockAdapter = require('axios-mock-adapter');

var mock = new MockAdapter(axios);

mock.onGet('/api/authorize'/).reply(200);

axios({
  method: 'get',
  url: '/api/authorize',
  auth: {
    username: 'foo',
    password: 'bar'
  }})
  .then(function(response) {
    console.log(response.status);
  });
```

Could you perhaps create a similar runnable example that reproduces your issue?

**Comment by ctimmerm** [comment] 2016-10-14 08:53
Since it has been hanging around for some time I'll close this one for now. Please reopen the issue if you have some runnable example where the issue is reproduced.

**Closed by ctimmerm** 2016-10-14 08:53 UTC

**Comment by tuzmusic** [comment] 2019-06-07 21:42
Is there a way to set a response only with the correct auth?
